camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

tenant: "oaf"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
  broker:
    contactpoint: "localhost:26500"
  init-transfer:
    wait-timer: 5

operations:
  host: http://ph-ee-operations-app
  base-url: /api/v1/errorcode
  filter-path: /filter

mpesa:
  max-retry-count: 2
  api:
    timeout: 60000
    lipana: /mpesa/stkpush/v1/processrequest
    transaction-status: /mpesa/stkpushquery/v1/query
  local:
    host: http://localhost:5000
    transaction-callback: /buygoods/callback
    queue-timeout-url: /queuetimeout/callback
    result-url: /result/callback

accounts:
  group:
    - name: "roster"
      business-short-code: ${ACCOUNTS_ROSTER_SHORTCODE:9383028}
      till: ${ACCOUNTS_ROSTER_TILL:1234567}
      auth-host:  ${ACCOUNTS_ROSTER_AUTHHOST:https://sandbox.safaricom.co.ke/oauth/v1/generate}
      client-key: ${ACCOUNTS_ROSTER_CLIENTKEY:0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5}
      client-secret:  ${ACCOUNTS_ROSTER_CLIENTSECRET:YzuGNoJxeub8ZC6d}
      api-host:  ${ACCOUNTS_ROSTER_APIHOST:https://sandbox.safaricom.co.ke}
      pass-key: ${ACCOUNTS_ROSTER_PASSKEY:bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919}
    - name: "paygops"
      business-short-code: ${ACCOUNTS_PAYGOPS_SHORTCODE:122344567}
      till: ${ACCOUNTS_PAYGOPS_TILL:1234567}
      auth-host: ${ACCOUNTS_PAYGOPS_AUTHHOST:https://sandbox.safaricom.co.ke/oauth/v1/generate}
      client-key: ${ACCOUNTS_PAYGOPS_CLIENTKEY:0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5}
      client-secret: ${ACCOUNTS_PAYGOPS_CLIENTSECRET:YzuGNoJxeub8ZC6d}
      api-host: ${ACCOUNTS_PAYGOPS_APIHOST:https://sandbox.safaricom.co.ke}
      pass-key: ${ACCOUNTS_PAYGOPS_PASSKEY:bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919}
    - name: "default"
      business-short-code:  ${ACCOUNTS_ROSTER_SHORTCODE:9383028}
      till: ${ACCOUNTS_ROSTER_TILL:1234567}
      auth-host:  ${ACCOUNTS_ROSTER_AUTHHOST:https://sandbox.safaricom.co.ke/oauth/v1/generate}
      client-key: ${ACCOUNTS_ROSTER_CLIENTKEY:0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5}
      client-secret:  ${ACCOUNTS_ROSTER_CLIENTSECRET:YzuGNoJxeub8ZC6d}
      api-host:  ${ACCOUNTS_ROSTER_APIHOST:https://sandbox.safaricom.co.ke}
      pass-key: ${ACCOUNTS_ROSTER_PASSKEY:bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919}

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true

skip:
  enabled : false

logging:
  level:
    root: INFO
