camel:
  server-port: 5000
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true

tenant: "oaf"

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
    ttl: 30000
  broker:
    contactpoint: "localhost:26500"

operations:
  host: https://paymenthub.qa.oneacrefund.org/opsapp
  base-url: /api/v1/errorcode
  filter-path: /filter

mpesa:
  business-short-code: 7385028
  till: 1234567
  max-retry-count: 3
  local:
    host: http://localhost:5000
    transaction-callback: /buygoods/callback
    queue-timeout-url: /queuetimeout/callback
    result-url: /result/callback
  auth:
    host: https://sandbox.safaricom.co.ke/oauth/v1/generate
    client-key: 0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5
    client-secret: YzuGNoJxeub8ZC6d
  api:
    host: https://sandbox.safaricom.co.ke
    lipana: /mpesa/stkpush/v1/processrequest
    transaction-status: /mpesa/stkpushquery/v1/query
    pass-key: bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true
